version: '3'

services:
  db-business-rules:
    image: postgres:9.6
    networks:
      - shared
    ports:
      - "5433:5432"
  business-rules:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    networks:
      - shared      
    ports:
      - "8001:8001"
    depends_on:
      - db-business-rules
    networks:
      - shared

  rabbitmq-docker:
    image: rabbitmq:3.7.3-management
    container_name: rabbitmq-docker
    ports:
    - "15672:15672"
    volumes:
    - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq.conf:ro
    - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - shared

networks:
  shared: 
    external:
      name: shared