# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-14 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LdaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=1000, unique=True)),
                ('creation_date', models.DateField(auto_now=True)),
                ('newest', models.BooleanField(default=True)),
                ('in_use', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_number', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('lda_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_ldamodel', to='topics.LdaModel')),
            ],
        ),
        migrations.CreateModel(
            name='TopicComparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('topic1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic1_topic2', to='topics.Topic')),
                ('topic2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic2_topic1', to='topics.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_topic', to='topics.Topic'),
        ),
        migrations.AlterUniqueTogether(
            name='topiccomparison',
            unique_together=set([('topic1_id', 'topic2_id')]),
        ),
    ]
