# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-17 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_topic', to='topics.Topic')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='topicuser',
            unique_together=set([('user_id', 'topic_id')]),
        ),
    ]
