# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-18 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20180917_2239'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topicuser',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='topicuser',
            name='topic_id',
        ),
        migrations.DeleteModel(
            name='TopicUser',
        ),
    ]
