# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-20 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_topic_coherence'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('topicComparison_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords_match', to='topics.TopicComparison')),
            ],
        ),
    ]
