# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-14 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('content_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DashboardUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SourceUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_source', to='user_preferences.Source')),
            ],
        ),
        migrations.CreateModel(
            name='TopicUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_topic', to='topics.Topic')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='contentuser',
            unique_together=set([('user_id', 'content_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='topicuser',
            unique_together=set([('user_id', 'topic_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='sourceuser',
            unique_together=set([('user_id', 'source_id')]),
        ),
    ]
