# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-18 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '0002_auto_20180909_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicuser',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_topic', to='topics.Topic'),
        ),
    ]
