# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-21 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '0005_auto_20181019_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergraph',
            name='name',
            field=models.CharField(default='Gráfico', max_length=30),
        ),
    ]
