# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-23 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '0006_usergraph_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicgraph',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_graph', to='user_preferences.TopicUser'),
        ),
    ]
