# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-27 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '0008_auto_20181023_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentuser',
            name='content_id',
            field=models.CharField(max_length=100),
        ),
    ]
