# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-19 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_dateconversion_saturday_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dateconversion',
            old_name='saturday_date',
            new_name='sunday_date',
        ),
    ]
