# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-19 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_auto_20181019_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateconversion',
            name='sunday_date',
            field=models.CharField(default='00/00/0000', max_length=15),
        ),
    ]
