# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-19 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_auto_20181019_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateconversion',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dateconversion',
            name='sunday_date',
            field=models.DateField(),
        ),
    ]
